server:
  port: 9191
spring:
  config:
    import: optional:configserver:http://localhost:9196
  application:
    name: PAYMENT-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"